#! /bin/bash
##
## A program to set up a Linux machine to be in ad-hoc mode
##       tested on Ubuntu 16.04.1 LTS
##
## Usage: adhoc nodeID [ssid]
##        The IP address will be 192.168.100.ID
##        The essid will be ssid or defaults to testnet
##        e.g., adhoc 1 dummynetwork makes it 192.168.100.1
##             and sets the essid to "dummynetwork"
##
##  Copyright (c) 2016, Autonomous Networks Research Group. All rights reserved.
##     Contributor: Bhaskar Krishnamachari
##     Read license file in main directory for more details
##

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
   echo "Usage: adhoc nodeID [ssid]" >&2
   echo "example: adhoc 1 dummynetwork" >&2
   exit 1
fi

if [ ! -z $2 ]; then SSID=$2; else SSID=testnet; fi

DEV=$(ifconfig -a |grep "Link encap"|grep wl|head -n1|cut -f 1 -d ' ')

echo "switching to ad hoc mode..."
sudo service network-manager stop
sleep 1
echo 5
sudo ip link set $DEV down
sleep 1
echo 4
sudo iwconfig $DEV mode ad-hoc
sleep 1
echo 3
sudo iwconfig $DEV essid $SSID
sleep 1
echo 2
sudo ip link set $DEV up
sleep 1
echo 1
sudo ip address add dev $DEV 192.168.100.$1/24
sleep 1
IPPREF=$(ip a s dev $DEV| grep inet | awk '/inet / {print $2}' | cut -f 1-3 -d '.')
echo "You are set up on ad-hoc mode on IP address $IPPREF.$1" 
